### ISSUE TITLE
Issue with for of loops

### ISSUE THREAD

**Issue by Kogoshvili** [TyrealHu/acorn-typescript#1]
Hi,

It seems that it has issue with `for of` loops
```typescript
function findLongestWord(sentence: string): number {
    const words = sentence.split(' ');
    let maxLength = 0;

    for (const word of words) {
        const length = word.length;

        if (length > maxLength) {
            maxLength = length;
        }
    }

    return maxLength;
}
```
![image](https://user-images.githubusercontent.com/75418606/227031512-dc180b46-8157-4f99-9757-524d30a8d1ed.png)

works if I replace for of with for loop.
works if I remove Typescript and used default acorn.

fails on v1.0.13 and v1.1.0

**Comment by TyrealHu** [comment]
@Kogoshvili This issue will be fixed at acorn-typescript@1.1.1
