### ISSUE TITLE
What do you think about introducing regression tests with test262-parser-runner?

### ISSUE THREAD

**Issue by ota-meshi** [TyrealHu/acorn-typescript#15]
First of all thank you for working on this acorn plugin for typescript.

I personally ran `test262-parser-runner`, which is also used by Acorn, on `acorn-typescript` fork repository and found some errors.

https://github.com/adrianheine/test262-parser-runner
https://github.com/TyrealHu/acorn-typescript/compare/master...ota-meshi:acorn-typescript:add-test262

Some tests still seem to fail, but I think it makes sense to introduce test262 so that we can share with you what is failing.

**Comment by TyrealHu** [comment]
OK, I will handle this problems

**Comment by ota-meshi** [comment]
I think we have introduced test262 and tested it, so I'm closing this issue. Thank you!
