### ISSUE TITLE
Parsing error in `1 < 2 > 3;`

### ISSUE THREAD

**Issue by ota-meshi** [TyrealHu/acorn-typescript#21]
The following code seems to give a parsing error when using acorn-typescript. I found this from test262 results.

```ts
1 < 2 > 3;
```

This is because `< 2 >` is judged as TypeArguments, and after that it cannot process subsequent code.
However, TypeScript parses this just fine.

By the way, the code below can be successfully parsed as an expression with TypeArguments.

```ts
1 < 2 >;
```

**Comment by TyrealHu** [comment]
it also seems to get an error in typescript`1 < 2 > 3` `Operator '>' cannot be applied to types 'boolean' and 'number'.`
https://www.typescriptlang.org/play?ts=4.8.4#code/IwAgPCBMIHwgzEA

**Comment by ota-meshi** [comment]
Thank you for letting me know. I may have made a mistake when checking :sweat: 
I will close this issue.
