### ISSUE TITLE
Missing internal deps

### ISSUE THREAD

**Issue by cecicifu** [TyrealHu/acorn-typescript#30]
Hi again! :)

The plugin works perfectly but is throwing some errors with internal dependencies.

**node_modules\acorn-typescript\lib\index.d.ts**

![image](https://github.com/TyrealHu/acorn-typescript/assets/15237067/58f641cb-c375-4261-a52b-776a5372d853)

Is it normal ? maybe is missing some dependencies in _package.json_ of plugin ?

My versions of dependencies:
![image](https://github.com/TyrealHu/acorn-typescript/assets/15237067/4f72fcc8-ced5-4fc1-a95b-5ee5a6438b72)

Thanks!

**Comment by TyrealHu** [comment]
this issue has been fixed at version 1.3.6

**Comment by cecicifu** [comment]
Thanks! 😊
