### ISSUE TITLE
Weird output using acorn-typescript as documented

### ISSUE THREAD

**Issue by NotYourFox** [TyrealHu/acorn-typescript#31]
For some reason parsing TypeScript source via
```acorn.Parser.extend(tsPlugin()).parse(ts, {ecmaVersion: 6, sourceType: this.mode});```
outputs the following when executed with node
[output.txt](https://github.com/TyrealHu/acorn-typescript/files/11735118/output.txt)

**Comment by TyrealHu** [comment]
I have added locations validation in `static parse`, `static parseExpression` and a notice in readme
